
# Configuración de la base de datos MySQL

[mysql]
host = "localhost"  # Cambia por tu host
port = 3306         # Puerto de MySQL (generalmente 3306)
database = "noti"   # Tu base de datos
user = "root" # Tu usuario de MySQL
password = "" # Tu contraseña de MySQL